version: "3.9"
services:
  user:
    image: "hapifriends/user"
    restart: always
    ports:
      - 9010:9010
  gateway:
    image: "hapifriends/gateway"
    restart: always
    ports:
      - 8080:8080
  admin:
   image: "hapifriends/admin"
   restart: always
   ports:
     - 9000:9000
