server.port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: userModule
          uri: http://localhost:9010/
          predicates:
            - Path=/**

  application:
    name: gateway-app
  boot:
    admin:
      url: http://localhost:9000

routes:management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always